name: .NET

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(jq -r .version package.json)

      - name: Set Release Name
        id: set_release_name
        run: echo "RELEASE_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.x  # Replace with the desired .NET version

      - name: Publish
        run: dotnet publish -c Release -o PLCsimAdvanced_manager

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'PLCsimAdvanced_manager.zip'
          path: './PLCsimAdvanced_manager/'

      - name: Create release body file
        uses: ultram4rine/extract-changes-action@v1
        with:
          changelog: CHANGELOG.md
          version: ${{ steps.get_version.outputs.VERSION }}
          output: changes.txt
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: PLCsimAdvanced_manager.zip
          body_path: changes.txt
  
  
  
