name: .NET

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Release Name
      id: set_release_name
      run: echo "RELEASE_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x  # Replace with the desired .NET version

    - name: Publish
      run: dotnet publish -c Release -o publish_output

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./publish_output/**
        release_name: ${{ env.RELEASE_NAME }}


